## Introduction to Data Science

### Saving, Accessing and Manipulating Data in different formats

[Additional info csv, xml and json](https://towardsdatascience.com/the-easy-way-to-work-with-csv-json-and-xml-in-python-5056f9325ca9)

In [1]:
import os
import sys
import time
import datetime
import numpy as np
import pandas as pd
import pathlib

In [2]:
datapath = pathlib.Path("../datasets/CSVs/")
datapath2 = pathlib.Path('../datasets/Miscellaneous/')
datapath3 = pathlib.Path('../datasets/Figs//')
outputs = pathlib.Path("../outputs/")

## Saving a txt file

In [3]:
with open(outputs / 'newfile.txt', mode='w', encoding='utf-8') as f:
    f.write('Weight\t\t72\n')
    f.write('Height\t\t183\n')
    f.write('Age\t\t44\n')
    f.write('Gender\t\tMasculine\n')
    f.write('\n')

## Retrieving a txt file

In [4]:
with open(outputs / 'newfile.txt', mode='r', encoding='utf-8') as f:
    fulltext = f.read()
    f.seek(0)
    line = f.readline()
    f.seek(0)
    list_of_lines = f.readlines()

In [5]:
print(fulltext)

Weight		72
Height		183
Age		44
Gender		Masculine




In [6]:
print(line)

Weight		72



In [7]:
print(list_of_lines)

['Weight\t\t72\n', 'Height\t\t183\n', 'Age\t\t44\n', 'Gender\t\tMasculine\n', '\n']


## Saving Numpy Structures

In [8]:
data = np.linspace(0,1,201)
print(data)

[0.    0.005 0.01  0.015 0.02  0.025 0.03  0.035 0.04  0.045 0.05  0.055
 0.06  0.065 0.07  0.075 0.08  0.085 0.09  0.095 0.1   0.105 0.11  0.115
 0.12  0.125 0.13  0.135 0.14  0.145 0.15  0.155 0.16  0.165 0.17  0.175
 0.18  0.185 0.19  0.195 0.2   0.205 0.21  0.215 0.22  0.225 0.23  0.235
 0.24  0.245 0.25  0.255 0.26  0.265 0.27  0.275 0.28  0.285 0.29  0.295
 0.3   0.305 0.31  0.315 0.32  0.325 0.33  0.335 0.34  0.345 0.35  0.355
 0.36  0.365 0.37  0.375 0.38  0.385 0.39  0.395 0.4   0.405 0.41  0.415
 0.42  0.425 0.43  0.435 0.44  0.445 0.45  0.455 0.46  0.465 0.47  0.475
 0.48  0.485 0.49  0.495 0.5   0.505 0.51  0.515 0.52  0.525 0.53  0.535
 0.54  0.545 0.55  0.555 0.56  0.565 0.57  0.575 0.58  0.585 0.59  0.595
 0.6   0.605 0.61  0.615 0.62  0.625 0.63  0.635 0.64  0.645 0.65  0.655
 0.66  0.665 0.67  0.675 0.68  0.685 0.69  0.695 0.7   0.705 0.71  0.715
 0.72  0.725 0.73  0.735 0.74  0.745 0.75  0.755 0.76  0.765 0.77  0.775
 0.78  0.785 0.79  0.795 0.8   0.805 0.81  0.815 0.

In [9]:
np.savetxt(outputs / 'data.dat', data)

In [10]:
data2 = np.loadtxt(outputs / 'data.dat')
print(data2)

[0.    0.005 0.01  0.015 0.02  0.025 0.03  0.035 0.04  0.045 0.05  0.055
 0.06  0.065 0.07  0.075 0.08  0.085 0.09  0.095 0.1   0.105 0.11  0.115
 0.12  0.125 0.13  0.135 0.14  0.145 0.15  0.155 0.16  0.165 0.17  0.175
 0.18  0.185 0.19  0.195 0.2   0.205 0.21  0.215 0.22  0.225 0.23  0.235
 0.24  0.245 0.25  0.255 0.26  0.265 0.27  0.275 0.28  0.285 0.29  0.295
 0.3   0.305 0.31  0.315 0.32  0.325 0.33  0.335 0.34  0.345 0.35  0.355
 0.36  0.365 0.37  0.375 0.38  0.385 0.39  0.395 0.4   0.405 0.41  0.415
 0.42  0.425 0.43  0.435 0.44  0.445 0.45  0.455 0.46  0.465 0.47  0.475
 0.48  0.485 0.49  0.495 0.5   0.505 0.51  0.515 0.52  0.525 0.53  0.535
 0.54  0.545 0.55  0.555 0.56  0.565 0.57  0.575 0.58  0.585 0.59  0.595
 0.6   0.605 0.61  0.615 0.62  0.625 0.63  0.635 0.64  0.645 0.65  0.655
 0.66  0.665 0.67  0.675 0.68  0.685 0.69  0.695 0.7   0.705 0.71  0.715
 0.72  0.725 0.73  0.735 0.74  0.745 0.75  0.755 0.76  0.765 0.77  0.775
 0.78  0.785 0.79  0.795 0.8   0.805 0.81  0.815 0.

In [11]:
x = np.linspace(0, 1, 20)
y = np.random.random(20)
header = "X-Column, Y-Column\n"
header += "This is a second line"

with open(outputs / 'data2.dat', 'wb') as f:
#with open(outputs / 'data2.dat', 'w') as f:   #using text formatting and no binary files
    np.savetxt(f, [], header=header)
    for i in range(20):
        data = np.column_stack((x[i], y[i]))
        np.savetxt(f, data), print(data)
        #f.write('{:4.1f} {:.4f}\n'.format(x[i], y[i]))    #using text formatting and no binary files
        f.flush()

[[0.         0.74323717]]
[[0.05263158 0.47339885]]
[[0.10526316 0.59716101]]
[[0.15789474 0.61335066]]
[[0.21052632 0.11946593]]
[[0.26315789 0.90633945]]
[[0.31578947 0.11381917]]
[[0.36842105 0.60659634]]
[[0.42105263 0.45403256]]
[[0.47368421 0.91076152]]
[[0.52631579 0.52970948]]
[[0.57894737 0.0088362 ]]
[[0.63157895 0.22975936]]
[[0.68421053 0.09459466]]
[[0.73684211 0.19553725]]
[[0.78947368 0.06313101]]
[[0.84210526 0.97673542]]
[[0.89473684 0.11682906]]
[[0.94736842 0.61214968]]
[[1.         0.48426655]]


In [12]:
! cat ../outputs/data2.dat

# X-Column, Y-Column
# This is a second line
0.000000000000000000e+00 7.432371698109303537e-01
5.263157894736841813e-02 4.733988504818925636e-01
1.052631578947368363e-01 5.971610138538376855e-01
1.578947368421052544e-01 6.133506611533304786e-01
2.105263157894736725e-01 1.194659336964386531e-01
2.631578947368420907e-01 9.063394468535985737e-01
3.157894736842105088e-01 1.138191666344308128e-01
3.684210526315789269e-01 6.065963372716890456e-01
4.210526315789473450e-01 4.540325551247034186e-01
4.736842105263157632e-01 9.107615248601377278e-01
5.263157894736841813e-01 5.297094763486214219e-01
5.789473684210526550e-01 8.836197853132721214e-03
6.315789473684210176e-01 2.297593606184347159e-01
6.842105263157893802e-01 9.459466170426644727e-02
7.368421052631578538e-01 1.955372460217442709e-01
7.894736842105263275e-01 6.313101046853319964e-02
8.421052631578946901e-01 9.767354237093872626e-01
8.947368421052630527e-01 1.168290620874751218e-01
9.473684210526315264e-01 6.121496755126265565e-01
1.000

## Using Pickle

In [13]:
import pickle

data = [1, 1.2, 'a', 'b']

with open(outputs / 'data.pkl', 'wb') as f:
    pickle.dump(data, f)

In [14]:
with open(outputs / 'data.pkl', 'rb') as f:
    new_data = pickle.load(f)

print(new_data)

[1, 1.2, 'a', 'b']


## Acessing CSV Files

In [15]:
csvfile = "beatles-diskography.csv"
datafile = datapath / csvfile

#### Using pure Python:

In [16]:
data = []
#with open(datafile, "r") as f:
with open(os.path.join("../datasets/CSVs/", csvfile), "r") as f:
    keys = f.readline().split(',')
    keys = [k.strip() for k in keys]
    for i in range(5):
        values = f.readline().split(',')
        values = [v.strip() for v in values]
        d = dict(zip(keys,values))
        data.append(d)
data[0:2]

[{'Title': 'Please Please Me',
  'Released': '22 March 1963',
  'Label': 'Parlophone(UK)',
  'UK Chart Position': '1',
  'US Chart Position': '-',
  'BPI Certification': 'Gold',
  'RIAA Certification': 'Platinum'},
 {'Title': 'With the Beatles',
  'Released': '22 November 1963',
  'Label': 'Parlophone(UK)',
  'UK Chart Position': '1',
  'US Chart Position': '-',
  'BPI Certification': 'Platinum',
  'RIAA Certification': 'Gold'}]

#### Using [CSV](https://docs.python.org/3/library/csv.html) module:

In [17]:
import csv

In [18]:
#with open(datafile, "r") as f:
with open(os.path.join("../datasets/CSVs/", csvfile), "r") as f:
    #data2 = csv.reader(f)
    data2 = csv.DictReader(f)
    for row in data2:
        print(row)

OrderedDict([('Title', 'Please Please Me'), ('Released', '22 March 1963'), ('Label', 'Parlophone(UK)'), ('UK Chart Position', '1'), ('US Chart Position', '-'), ('BPI Certification', 'Gold'), ('RIAA Certification', 'Platinum')])
OrderedDict([('Title', 'With the Beatles'), ('Released', '22 November 1963'), ('Label', 'Parlophone(UK)'), ('UK Chart Position', '1'), ('US Chart Position', '-'), ('BPI Certification', 'Platinum'), ('RIAA Certification', 'Gold')])
OrderedDict([('Title', 'Beatlemania! With the Beatles'), ('Released', '25 November 1963'), ('Label', 'Capitol(CAN)'), ('UK Chart Position', '-'), ('US Chart Position', '-'), ('BPI Certification', ''), ('RIAA Certification', '')])
OrderedDict([('Title', 'Introducing... The Beatles'), ('Released', '10 January 1964'), ('Label', 'Vee-Jay(US)'), ('UK Chart Position', '-'), ('US Chart Position', '2'), ('BPI Certification', ''), ('RIAA Certification', '')])
OrderedDict([('Title', 'Meet the Beatles!'), ('Released', '20 January 1964'), ('Label'

#### Using Pandas:

In [19]:
df_csv = pd.read_csv(datafile)
df_csv.head()
#df_csv.info()

Title          Released           Label  \
0               Please Please Me     22 March 1963  Parlophone(UK)   
1               With the Beatles  22 November 1963  Parlophone(UK)   
2  Beatlemania! With the Beatles  25 November 1963    Capitol(CAN)   
3     Introducing... The Beatles   10 January 1964     Vee-Jay(US)   
4              Meet the Beatles!   20 January 1964     Capitol(US)   

  UK Chart Position US Chart Position BPI Certification RIAA Certification  
0                 1                 -              Gold           Platinum  
1                 1                 -          Platinum               Gold  
2                 -                 -               NaN                NaN  
3                 -                 2               NaN                NaN  
4                 -                 1               NaN         5xPlatinum

## Manipulating [Zip Files](https://docs.python.org/3/library/zipfile.html)

In [20]:
from zipfile import ZipFile

In [29]:
compressedfile = "2013_ERCOT_Hourly_Load_Data"

In [35]:
with ZipFile('{0}.zip'.format(datapath / compressedfile), 'r') as myzip:
    #with myzip.open('2013_ERCOT_Hourly_Load_Data.xls') as myfile:
    #    pd_excel = pd.read_excel(myfile)
    myzip.extract('{0}.xls'.format(compressedfile))
                  
pd_excel = pd.read_excel('{0}.xls'.format(datapath / compressedfile))
pd_excel.head()


Hour_End        COAST         EAST     FAR_WEST       NORTH  \
0 2013-01-01 01:00:00  7606.263544  1073.892438  1411.750567  784.978166   
1 2013-01-01 02:00:00  7388.082714  1035.021938  1403.472287  776.307387   
2 2013-01-01 03:00:00  7178.867878  1036.088697  1395.053150  768.125748   
3 2013-01-01 04:00:00  7038.822581  1032.648841  1395.508820  770.937969   
4 2013-01-01 05:00:00  6990.857940  1042.823044  1401.216842  779.089313   

        NORTH_C     SOUTHERN      SOUTH_C        WEST         ERCOT  
0  10369.094390  2206.675077  4368.490945  882.931901  28704.077028  
1  10152.358518  2159.733208  4233.587967  872.404750  28020.968769  
2   9988.051418  2065.114706  4082.862860  868.853938  27383.018395  
3   9946.658655  1990.903699  4010.489608  865.701201  27051.671374  
4  10096.664190  1954.807585  4038.655997  879.924249  27184.039160

## [Acessing](https://pypi.python.org/pypi/xlrd) and [Writing](https://pypi.python.org/pypi/xlwt) [Excel Files](https://github.com/python-excel/tutorial/blob/master/python-excel.pdf)

#### Accessing a workbook

In [36]:
import xlrd

In [37]:
datafile = "2013_ERCOT_Hourly_Load_Data.xls"

In [38]:
with ZipFile('{0}.zip'.format(datapath / zipfile), 'r') as myzip:
    myzip.extractall(datapath)

In [39]:
workbook = xlrd.open_workbook(datapath / datafile)
sheet = workbook.sheet_by_index(0)

In [40]:
sheet_data = [[sheet.cell_value(r, col) for col in range(sheet.ncols)] for r in range(sheet.nrows)]
sheet_data[:2]

[['Hour_End',
  'COAST',
  'EAST',
  'FAR_WEST',
  'NORTH',
  'NORTH_C',
  'SOUTHERN',
  'SOUTH_C',
  'WEST',
  'ERCOT'],
 [41275.041666666664,
  7606.263544000012,
  1073.892438,
  1411.7505669999982,
  784.9781659999992,
  10369.094390000051,
  2206.6750770000012,
  4368.490945000006,
  882.9319009999975,
  28704.077028000065]]

In [41]:
print("Number of rows in the sheet:"),
print(sheet.nrows)

Number of rows in the sheet:
7296


In [42]:
print("Type of data in cell (row 3, col 2):"), 
print(sheet.cell_type(3, 2))

Type of data in cell (row 3, col 2):
2


In [43]:
print("Value in cell (row 3, col 2):", )
print(sheet.cell_value(3, 2))

Value in cell (row 3, col 2):
1036.0886969999988


In [44]:
print("Get a slice of values in column 3, from rows 1-3:",)
print(sheet.col_values(3, start_rowx=1, end_rowx=4))

Get a slice of values in column 3, from rows 1-3:
[1411.7505669999982, 1403.4722870000019, 1395.053150000001]


In [45]:
coast = sheet.col_values(1, start_rowx=1)
data3 = {}    
data3['maxvalue'] = max(coast)
data3['minvalue'] = min(coast)
data3['avgcoast'] = np.mean(coast)

rowmax = coast.index(max(coast))+1
rowmin = coast.index(min(coast))+1

data3['maxtime'] = xlrd.xldate_as_tuple(sheet.cell_value(rowmax,0), 0)
data3['mintime'] = xlrd.xldate_as_tuple(sheet.cell_value(rowmin,0), 0)

In [46]:
data3

{'maxvalue': 18779.025510000003,
 'minvalue': 6602.113898999982,
 'avgcoast': 10976.933460679784,
 'maxtime': (2013, 8, 13, 17, 0, 0),
 'mintime': (2013, 2, 3, 4, 0, 0)}

#### Using Pandas

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_excel.html  

In [47]:
pd_excel = pd.read_excel(datapath / datafile)
pd_excel.head()

Hour_End        COAST         EAST     FAR_WEST       NORTH  \
0 2013-01-01 01:00:00  7606.263544  1073.892438  1411.750567  784.978166   
1 2013-01-01 02:00:00  7388.082714  1035.021938  1403.472287  776.307387   
2 2013-01-01 03:00:00  7178.867878  1036.088697  1395.053150  768.125748   
3 2013-01-01 04:00:00  7038.822581  1032.648841  1395.508820  770.937969   
4 2013-01-01 05:00:00  6990.857940  1042.823044  1401.216842  779.089313   

        NORTH_C     SOUTHERN      SOUTH_C        WEST         ERCOT  
0  10369.094390  2206.675077  4368.490945  882.931901  28704.077028  
1  10152.358518  2159.733208  4233.587967  872.404750  28020.968769  
2   9988.051418  2065.114706  4082.862860  868.853938  27383.018395  
3   9946.658655  1990.903699  4010.489608  865.701201  27051.671374  
4  10096.664190  1954.807585  4038.655997  879.924249  27184.039160

#### Reading and Writing a Workbook

In [48]:
import xlwt

In [49]:
style0 = xlwt.easyxf('font: name Times New Roman, color-index red, bold on', num_format_str='#,##0.00')
style1 = xlwt.easyxf(num_format_str='D-MMM-YY')

In [50]:
workbook = xlwt.Workbook()
workbook_name = 'my_workbook.xls'

worksheet1 = workbook.add_sheet('my_first_sheet')
worksheet1.write(0, 0, 'Column 1 title', style0)
worksheet1.write(0, 1, 'Column 2 title', style0)

worksheet2 = workbook.add_sheet('my_second_sheet')
worksheet2.write(0, 0, 'Itens')
worksheet2.write(0, 1, 'Price')
worksheet2.write(1, 0, 'Rice')
worksheet2.write(1, 1, 100)
worksheet2.write(2, 0, 'Beans')
worksheet2.write(2, 1, 200)
worksheet2.write(3, 0, 'Pasta')
worksheet2.write(3, 1, 500)
worksheet2.write(5, 0, 'Total')

worksheet2.write(5, 1, xlwt.Formula("B2+B3+B4"))


workbook.save(outputs / workbook_name)

### Reading PDF Files  

More resources [here](https://textract.readthedocs.io/en/stable/) and [here](https://towardsdatascience.com/python-for-pdf-ef0fac2808b0?)

In [51]:
import textract

In [52]:
onlyfiles = [f for f in os.listdir(datapath2) if os.path.isfile(datapath2 / f) and f.endswith('.pdf')]
onlyfiles.sort()

print('Files in the folder:')
for i, w in enumerate(onlyfiles):
    print(i+1, '--' ,w)

Files in the folder:
1 -- Useful_Things_ML.pdf


In [53]:
text0 = textract.process(datapath2 / onlyfiles[0]).decode('utf-8')
print(text0[0:1000])

A Few Useful Things to Know about Machine Learning
Pedro Domingos
Department of Computer Science and Engineering
University of Washington
Seattle, WA 98195-2350, U.S.A.

pedrod@cs.washington.edu

ABSTRACT
Machine learning algorithms can figure out how to perform
important tasks by generalizing from examples. This is often feasible and cost-effective where manual programming
is not. As more data becomes available, more ambitious
problems can be tackled. As a result, machine learning is
widely used in computer science and other fields. However,
developing successful machine learning applications requires
a substantial amount of “black art” that is hard to find in
textbooks. This article summarizes twelve key lessons that
machine learning researchers and practitioners have learned.
These include pitfalls to avoid, important issues to focus on,
and answers to common questions.

correct output yt for future examples xt (e.g., whether the
spam filter correctly classifies previously unseen em

### Reading Text in Image Files (OCR)

In [54]:
onlyfiles = [f for f in os.listdir(datapath3) if os.path.isfile(datapath3 / f) and f.endswith('.png')]
onlyfiles.sort()

print('Files in the folder:')
for i, w in enumerate(onlyfiles):
    print(i+1, '--' ,w)

Files in the folder:
1 -- Cov_nonstationary.png
2 -- K-means.png
3 -- Mean_nonstationary.png
4 -- Modeling1.png
5 -- Modeling2.png
6 -- Modeling4.png
7 -- Var_nonstationary.png
8 -- aristotle-wikipedia.png
9 -- binning.png
10 -- db_schema.png
11 -- decision_tree.png
12 -- dimreduxsummary.png
13 -- entities1.png
14 -- entities2.png
15 -- framework.png
16 -- groupby-example.png
17 -- hclustering-1.png
18 -- hclustering-2.png
19 -- lenet_architecture-768x226.png
20 -- machine-learning-cheet-sheet.png
21 -- modeling3.png
22 -- neuralnet.png
23 -- neuralnet2.png
24 -- neuralnet3.png
25 -- neuralnet4.png
26 -- nmf.png
27 -- pca_ica.png
28 -- pca_ica2.png
29 -- pca_ica3.png
30 -- project1.png
31 -- project2.png
32 -- project3.png
33 -- project4.png
34 -- sample_graph.png
35 -- saturn.png
36 -- straight_line.png
37 -- summary_redux_dim_techniques.png
38 -- sup-unsup.png
39 -- textimage.png
40 -- transform-example.png
41 -- transmission.png
42 -- tsne1.png
43 -- tsne2.png
44 -- vehicle_class.pn

In [56]:
datapath3 / 'textimage.png'

PosixPath('../datasets/Figs/textimage.png')

In [59]:
text1 = textract.process(datapath3 / 'textimage.png').decode('utf-8')
print(text1[0:900])

Adobe, the Adobe logo, Acrobat, the Acrobat logo, Acrobat Capture, Adobe Garamond, Adobe
Intelligent Document Platform, Adobe PDF, Adobe Reader, Adobe Solutions Network, Aldus, Dis-
tiller, ePaper, Extreme, FrameMaker, Illustrator, InDesign, Minion, Myriad, PageMaker, Photo-
shop, Poetica, PostScript, and XMP are either registered trademarks or trademarks of Adobe
‘Systems Incorporated in the United States and/or other countries. Microsoft and Windows are
either registered trademarks or trademarks of Microsoft Corporation in the United States and/or
other countries. Apple, Mac, Macintosh, and Power Macintosh are trademarks of Apple Computer,
Inc,, registered in the United States and other countries. IBM is a registered trademark of IBM
Corporation in the United States. Sun is a trademark or registered trademark of Sun Microsys-
tems, Inc. in the United States and other countries. UNIX is


## Accessing HTML

https://docs.python.org/3/library/urllib.html  
http://www.crummy.com/software/BeautifulSoup/  
http://docs.python-requests.org/en/latest/  
http://lxml.de/  
https://docs.python.org/3/library/getpass.html  

In [60]:
import urllib
from bs4 import BeautifulSoup as bs
import requests
import lxml.html
import getpass

In [61]:
url = "http://oglobo.globo.com"
html_txt = urllib.request.urlopen(url).read()
soup = bs(html_txt, "html.parser")
 
[line.get('href') for line in soup.find_all('a')][0:10]    

['https://oglobo.globo.com/',
 '#main-nav',
 'https://www.facebook.com/jornaloglobo',
 'https://twitter.com/jornaloglobo',
 'https://www.instagram.com/jornaloglobo',
 'https://oglobo.globo.com/rio/',
 'https://oglobo.globo.com/brasil/',
 'https://oglobo.globo.com/mundo/',
 'https://oglobo.globo.com/economia/',
 'https://oglobo.globo.com/cultura/']

#### Another approach: [lxml](http://lxml.de/tutorial.html) instead of beautiful soup
 

In [62]:
url = "http://www.hotashtanga.com/p/letoltesek-downloads.html"
html_txt = urllib.request.urlopen(url).read()
dom =  lxml.html.fromstring(html_txt)
    
[line for line in dom.xpath('//a/@href')][0:10]   

['http://www.hotashtanga.com/',
 'http://www.hotashtanga.com/',
 'http://www.hotashtanga.com/p/szolgaltatasok.html',
 'http://www.hotashtanga.com/p/letoltesek-downloads.html',
 'http://www.hotashtanga.com/p/eletrajz.html',
 'http://www.hotashtanga.com/p/kapcsolat-contact-me.html',
 '//www.blogger.com/rearrange?blogID=2389334795161374820&widgetType=PageList&widgetId=PageList1&action=editWidget&sectionId=crosscol',
 'https://drive.google.com/open?id=0B0t9QIGAtRQ5eGVjNDFaQmFhZXM',
 'https://drive.google.com/open?id=0B0t9QIGAtRQ5dnJEamZaWmpieGs',
 'https://drive.google.com/open?id=0B0t9QIGAtRQ5eGMzX0U4ZVFNNjA']

#### Using [Requests](http://docs.python-requests.org/en/master/user/quickstart/), for more complex tasks  


c.f. [HTML Responses](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)

In [70]:
p = getpass.getpass()
r = requests.get('https://api.github.com/user', auth=('rsouza', p))
r.status_code

 ············


200

In [71]:
r.headers['content-type']

'application/json; charset=utf-8'

In [72]:
r.encoding

'utf-8'

In [73]:
r.text

'{"login":"rsouza","id":604914,"node_id":"MDQ6VXNlcjYwNDkxNA==","avatar_url":"https://avatars0.githubusercontent.com/u/604914?v=4","gravatar_id":"","url":"https://api.github.com/users/rsouza","html_url":"https://github.com/rsouza","followers_url":"https://api.github.com/users/rsouza/followers","following_url":"https://api.github.com/users/rsouza/following{/other_user}","gists_url":"https://api.github.com/users/rsouza/gists{/gist_id}","starred_url":"https://api.github.com/users/rsouza/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rsouza/subscriptions","organizations_url":"https://api.github.com/users/rsouza/orgs","repos_url":"https://api.github.com/users/rsouza/repos","events_url":"https://api.github.com/users/rsouza/events{/privacy}","received_events_url":"https://api.github.com/users/rsouza/received_events","type":"User","site_admin":false,"name":"Renato Rocha Souza","company":"ÖAW-ACDH | FGV | UFMG","blog":"https://www.oeaw.ac.at/acdh/team/current-team/ren

In [74]:
r.json()

{'login': 'rsouza',
 'id': 604914,
 'node_id': 'MDQ6VXNlcjYwNDkxNA==',
 'avatar_url': 'https://avatars0.githubusercontent.com/u/604914?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/rsouza',
 'html_url': 'https://github.com/rsouza',
 'followers_url': 'https://api.github.com/users/rsouza/followers',
 'following_url': 'https://api.github.com/users/rsouza/following{/other_user}',
 'gists_url': 'https://api.github.com/users/rsouza/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/rsouza/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/rsouza/subscriptions',
 'organizations_url': 'https://api.github.com/users/rsouza/orgs',
 'repos_url': 'https://api.github.com/users/rsouza/repos',
 'events_url': 'https://api.github.com/users/rsouza/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/rsouza/received_events',
 'type': 'User',
 'site_admin': False,
 'name': 'Renato Rocha Souza',
 'company': 'ÖAW-ACDH | FGV | UFMG',

## Accessing [JSON](http://json.org/)

https://docs.python.org/3/library/json.html  
https://docs.python.org/3/library/urllib.html  

In [75]:
import json

In [76]:
base_url = "http://musicbrainz.org/ws/2/"
artist_url =  urllib.parse.urljoin(base_url, 'artist/')
query_type = {"simple": {},
              "atr": {"inc": "aliases+tags+ratings"},
              "aliases": {"inc": "aliases"},
              "releases": {"inc": "releases"}}

In [77]:
def query_site(url, params, uid="", fmt="json"):
    params["fmt"] = fmt
    r = requests.get(url + uid, params=params)
    print("requesting", r.url)

    if r.status_code == requests.codes.ok:
        return r.json()
    else:
        r.raise_for_status()

In [78]:
def query_by_name(url, params, name):
    params["query"] = "artist:" + name
    return query_site(url, params)

In [79]:
def pretty_print(data, indent=4):
    if type(data) == dict:
        print(json.dumps(data, indent=indent, sort_keys=True))
    else:
        print(data)

In [80]:
results = query_by_name(artist_url, query_type["simple"], "Nirvana")
pretty_print(results['artists'])

requesting http://musicbrainz.org/ws/2/artist/?query=artist%3ANirvana&fmt=json
[{'id': '5b11f4ce-a62d-471e-81fc-a69a8278c7da', 'type': 'Group', 'type-id': 'e431f5f6-b5d2-343d-8b36-72607fffb74b', 'score': 100, 'name': 'Nirvana', 'sort-name': 'Nirvana', 'country': 'US', 'area': {'id': '489ce91b-6658-3307-9877-795b68554c98', 'type': 'Country', 'type-id': '06dd0ae4-8c74-30bb-b43d-95dcedf961de', 'name': 'United States', 'sort-name': 'United States', 'life-span': {'ended': None}}, 'begin-area': {'id': 'a640b45c-c173-49b1-8030-973603e895b5', 'type': 'City', 'type-id': '6fd8f29a-3d0a-32fc-980d-ea697b69da78', 'name': 'Aberdeen', 'sort-name': 'Aberdeen', 'life-span': {'ended': None}}, 'disambiguation': '90s US grunge band', 'isnis': ['0000000123486830', '0000000123487390'], 'life-span': {'begin': '1988-01', 'end': '1994-04-05', 'ended': True}, 'aliases': [{'sort-name': 'ニルヴァーナ', 'type-id': '894afba6-2816-3c24-8072-eadb66bd04bc', 'name': 'ニルヴァーナ', 'locale': 'ja', 'type': 'Artist name', 'primary':

In [81]:
results.keys()

dict_keys(['created', 'count', 'offset', 'artists'])

In [82]:
print("\nARTIST:")
pretty_print(results["artists"][4])


ARTIST:
{
    "area": {
        "id": "6a264f94-6ff1-30b1-9a81-41f7bfabd616",
        "life-span": {
            "ended": null
        },
        "name": "Finland",
        "sort-name": "Finland",
        "type": "Country",
        "type-id": "06dd0ae4-8c74-30bb-b43d-95dcedf961de"
    },
    "country": "FI",
    "disambiguation": "Early 1980's Finnish punk band",
    "id": "85af0709-95db-4fbc-801a-120e9f4766d0",
    "life-span": {
        "ended": null
    },
    "name": "Nirvana",
    "score": 71,
    "sort-name": "Nirvana",
    "tags": [
        {
            "count": 1,
            "name": "punk"
        },
        {
            "count": 1,
            "name": "finland"
        }
    ],
    "type": "Group",
    "type-id": "e431f5f6-b5d2-343d-8b36-72607fffb74b"
}


In [83]:
artist_id = results["artists"][4]["id"]
artist_id

'85af0709-95db-4fbc-801a-120e9f4766d0'

In [84]:
artist_data = query_site(artist_url, query_type["releases"], artist_id)
releases = artist_data["releases"]
print("\nONE RELEASE:")
pretty_print(releases[0], indent=2)

requesting http://musicbrainz.org/ws/2/artist/85af0709-95db-4fbc-801a-120e9f4766d0?inc=releases&fmt=json

ONE RELEASE:
{
  "barcode": "",
  "country": "FI",
  "date": "1980",
  "disambiguation": "",
  "id": "3e25396c-5c66-4609-8e47-37f250d323c7",
  "packaging": "Cardboard/Paper Sleeve",
  "packaging-id": "f7101ce3-0384-39ce-9fde-fbbd0044d35f",
  "quality": "normal",
  "release-events": [
    {
      "area": {
        "disambiguation": "",
        "id": "6a264f94-6ff1-30b1-9a81-41f7bfabd616",
        "iso-3166-1-codes": [
          "FI"
        ],
        "name": "Finland",
        "sort-name": "Finland"
      },
      "date": "1980"
    }
  ],
  "status": "Official",
  "status-id": "4e304316-386d-3409-af2e-78857eec5cfe",
  "text-representation": {
    "language": "fin",
    "script": "Latn"
  },
  "title": "Nirvana"
}


In [85]:
releases

[{'packaging-id': 'f7101ce3-0384-39ce-9fde-fbbd0044d35f',
  'status': 'Official',
  'quality': 'normal',
  'barcode': '',
  'packaging': 'Cardboard/Paper Sleeve',
  'disambiguation': '',
  'date': '1980',
  'release-events': [{'area': {'sort-name': 'Finland',
     'name': 'Finland',
     'id': '6a264f94-6ff1-30b1-9a81-41f7bfabd616',
     'disambiguation': '',
     'iso-3166-1-codes': ['FI']},
    'date': '1980'}],
  'text-representation': {'language': 'fin', 'script': 'Latn'},
  'title': 'Nirvana',
  'id': '3e25396c-5c66-4609-8e47-37f250d323c7',
  'status-id': '4e304316-386d-3409-af2e-78857eec5cfe',
  'country': 'FI'}]

In [86]:
release_titles = [r["title"] for r in releases]
print("\nALL TITLES:")
for t in release_titles:
        print(t)


ALL TITLES:
Nirvana


#### Using Pandas

http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader  

In [87]:
df_json = pd.read_json('https://api.github.com/repos/pydata/pandas/issues?per_page=5')
df_json

url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   

                                   repository_url  \
0  https://api.github.com/repos/pandas-dev/pandas   
1  https://api.github.com/repos/pandas-dev/pandas   
2  https://api.github.com/repos/pandas-dev/pandas   
3  https://api.github.com/repos/pandas-dev/pandas   
4  https://api.github.com/repos/pandas-dev/pandas   

                                          labels_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   

                                        comments_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   

                                          events_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   

                                            html_url         id  \
0  https://github.com/pandas-dev/pandas/issues/29835  528170077   
1  https://github.com/pandas-dev/pandas/issues/29834  528129533   
2  https://github.com/pandas-dev/pandas/issues/29833  527889585   
3  https://github.com/pandas-dev/pandas/issues/29832  527872894   
4    https://github.com/pandas-dev/pandas/pull/29831  527812463   

                            node_id  number  \
0          MDU6SXNzdWU1MjgxNzAwNzc=   29835   
1          MDU6SXNzdWU1MjgxMjk1MzM=   29834   
2          MDU6SXNzdWU1Mjc4ODk1ODU=   29833   
3          MDU6SXNzdWU1Mjc4NzI4OTQ=   29832   
4  MDExOlB1bGxSZXF1ZXN0MzQ0OTg5Njk1   29831   

                                               title  ... assignee assignees  \
0  deleting index column but index=False not working  ...      NaN        []   
1  pivot_table with MultiIndex and margin=True fa...  ...      NaN        []   
2  Aggregation fails when grouping on more than o...  ...      NaN        []   
3  read_hdf() file name encoding with with accent...  ...      NaN        []   
4                          DEPR: Remove weekday_name  ...      NaN        []   

  milestone  comments                created_at                updated_at  \
0       NaN         0 2019-11-25 15:43:35+00:00 2019-11-25 15:43:35+00:00   
1       NaN         0 2019-11-25 14:38:06+00:00 2019-11-25 14:38:06+00:00   
2       NaN         1 2019-11-25 07:02:02+00:00 2019-11-25 11:20:00+00:00   
3       NaN         1 2019-11-25 06:16:51+00:00 2019-11-25 12:12:46+00:00   
4       NaN         1 2019-11-25 02:50:41+00:00 2019-11-25 15:46:44+00:00   

   closed_at  author_association  \
0        NaT                NONE   
1        NaT                NONE   
2        NaT                NONE   
3        NaT                NONE   
4        NaT              MEMBER   

                                                body  \
0  #### Code Sample, a copy-pastable example if p...   
1  #### Code Sample, a copy-pastable example if p...   
2  #### Code Sample, a copy-pastable example if p...   
3  #### Problem description\r\n\r\npd.read_hdf() ...   
4  - [x] xref #18164\r\n- [x] tests added / passe...   

                                        pull_request  
0                                                NaN  
1                                                NaN  
2                                

## Accessing YAML

In [88]:
import yaml

In [89]:
with open(datapath / 'simple.yaml', 'r') as stream:
    try:
        print(yaml.load(stream))
    except yaml.YAMLError as exc:
        print(exc)

[{'martin': {'name': "Martin D'vloper", 'job': 'Developer', 'skills': ['python', 'perl', 'pascal']}}, {'tabitha': {'name': 'Tabitha Bitumen', 'job': 'Developer', 'skills': ['lisp', 'fortran', 'erlang']}}]


/home/rsouza/Documents/envs/python_env/lib/python3.6/site-packages/ipykernel_launcher.py:3: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  This is separate from the ipykernel package so we can avoid doing imports until


## Accessing XML

https://docs.python.org/3/library/urllib.html

https://docs.python.org/3/library/xml.etree.elementtree.html

http://lxml.de/

http://www.w3schools.com/xml/xml_examples.asp

In [90]:
from xml.dom import minidom
#from xml.etree import ElementTree as ET
from lxml import etree as ET #Supports xpath syntax
from collections import defaultdict
from pprint import pprint

In [91]:
url = 'http://www.w3schools.com/xml/cd_catalog.xml'
xml_page = urllib.request.urlopen(url).read()
e = ET.XML(xml_page)

In [92]:
def etree_to_dict(t):
    d = {t.tag: {} if t.attrib else None}
    children = list(t)
    if children:
        dd = defaultdict(list)
        for dc in map(etree_to_dict, children):
            for k, v in dc.items():
                dd[k].append(v)
        d = {t.tag: {k:v[0] if len(v) == 1 else v for k, v in dd.items()}}
    if t.attrib:
        d[t.tag].update(('@' + k, v) for k, v in t.attrib.items())
    if t.text:
        text = t.text.strip()
        if children or t.attrib:
            if text:
              d[t.tag]['#text'] = text
        else:
            d[t.tag] = text
    return d

In [93]:
pprint(etree_to_dict(e))

{'CATALOG': {'CD': [{'ARTIST': 'Bob Dylan',
                     'COMPANY': 'Columbia',
                     'COUNTRY': 'USA',
                     'PRICE': '10.90',
                     'TITLE': 'Empire Burlesque',
                     'YEAR': '1985'},
                    {'ARTIST': 'Bonnie Tyler',
                     'COMPANY': 'CBS Records',
                     'COUNTRY': 'UK',
                     'PRICE': '9.90',
                     'TITLE': 'Hide your heart',
                     'YEAR': '1988'},
                    {'ARTIST': 'Dolly Parton',
                     'COMPANY': 'RCA',
                     'COUNTRY': 'USA',
                     'PRICE': '9.90',
                     'TITLE': 'Greatest Hits',
                     'YEAR': '1982'},
                    {'ARTIST': 'Gary Moore',
                     'COMPANY': 'Virgin records',
                     'COUNTRY': 'UK',
                     'PRICE': '10.20',
                     'TITLE': 'Still got the blues',
                

In [94]:
raw_page = urllib.request.urlopen(url)
doc = minidom.parse(raw_page)

def findTextnodes(nodeList):
    for subnode in nodeList:
        if subnode.nodeType == subnode.ELEMENT_NODE:
            print("Element node: " + subnode.tagName)
            findTextnodes(subnode.childNodes)
        elif subnode.nodeType == subnode.TEXT_NODE:
            print("text node:" + subnode.data)
            
findTextnodes(doc.childNodes)

Element node: CATALOG
text node:
  
Element node: CD
text node:
    
Element node: TITLE
text node:Empire Burlesque
text node:
    
Element node: ARTIST
text node:Bob Dylan
text node:
    
Element node: COUNTRY
text node:USA
text node:
    
Element node: COMPANY
text node:Columbia
text node:
    
Element node: PRICE
text node:10.90
text node:
    
Element node: YEAR
text node:1985
text node:
  
text node:
  
Element node: CD
text node:
    
Element node: TITLE
text node:Hide your heart
text node:
    
Element node: ARTIST
text node:Bonnie Tyler
text node:
    
Element node: COUNTRY
text node:UK
text node:
    
Element node: COMPANY
text node:CBS Records
text node:
    
Element node: PRICE
text node:9.90
text node:
    
Element node: YEAR
text node:1988
text node:
  
text node:
  
Element node: CD
text node:
    
Element node: TITLE
text node:Greatest Hits
text node:
    
Element node: ARTIST
text node:Dolly Parton
text node:
    
Element node: COUNTRY
text node:USA
text node:
    
Elem

In [95]:
root = ET.fromstring(xml_page)
cdtags = root.xpath('//CD/TITLE')
for cd in cdtags:
    print(cd.text)

Empire Burlesque
Hide your heart
Greatest Hits
Still got the blues
Eros
One night only
Sylvias Mother
Maggie May
Romanza
When a man loves a woman
Black angel
1999 Grammy Nominees
For the good times
Big Willie style
Tupelo Honey
Soulsville
The very best of
Stop
Bridge of Spies
Private Dancer
Midt om natten
Pavarotti Gala Concert
The dock of the bay
Picture book
Red
Unchain my heart


In [96]:
for cd in root.findall('CD'):
    title = cd.find('TITLE').text
    artist = cd.find('ARTIST').text
    country = cd.find('COUNTRY').text
    print('{}\t{}\t{}'.format(artist, country, title))

Bob Dylan	USA	Empire Burlesque
Bonnie Tyler	UK	Hide your heart
Dolly Parton	USA	Greatest Hits
Gary Moore	UK	Still got the blues
Eros Ramazzotti	EU	Eros
Bee Gees	UK	One night only
Dr.Hook	UK	Sylvias Mother
Rod Stewart	UK	Maggie May
Andrea Bocelli	EU	Romanza
Percy Sledge	USA	When a man loves a woman
Savage Rose	EU	Black angel
Many	USA	1999 Grammy Nominees
Kenny Rogers	UK	For the good times
Will Smith	USA	Big Willie style
Van Morrison	UK	Tupelo Honey
Jorn Hoel	Norway	Soulsville
Cat Stevens	UK	The very best of
Sam Brown	UK	Stop
T'Pau	UK	Bridge of Spies
Tina Turner	UK	Private Dancer
Kim Larsen	EU	Midt om natten
Luciano Pavarotti	UK	Pavarotti Gala Concert
Otis Redding	USA	The dock of the bay
Simply Red	EU	Picture book
The Communards	UK	Red
Joe Cocker	USA	Unchain my heart


In [97]:
cds = []
for cd in root.findall('./CD'):
        data = {}
        data["TITLE"] = cd.find('./TITLE').text
        data["ARTIST"] = cd.find('./ARTIST').text
        data["COUNTRY"] = cd.find('./COUNTRY').text
        data["PRICE"] = cd.find('./PRICE').text
        data["YEAR"] = cd.find('./YEAR').text
        cds.append(data)
cds[0:3]

[{'TITLE': 'Empire Burlesque',
  'ARTIST': 'Bob Dylan',
  'COUNTRY': 'USA',
  'PRICE': '10.90',
  'YEAR': '1985'},
 {'TITLE': 'Hide your heart',
  'ARTIST': 'Bonnie Tyler',
  'COUNTRY': 'UK',
  'PRICE': '9.90',
  'YEAR': '1988'},
 {'TITLE': 'Greatest Hits',
  'ARTIST': 'Dolly Parton',
  'COUNTRY': 'USA',
  'PRICE': '9.90',
  'YEAR': '1982'}]

## Acessing Databases

### Acessing [SQLite](https://docs.python.org/3/library/sqlite3.html)  

In [98]:
import sqlite3
conn = sqlite3.connect(os.path.join(outputs,'example.db'))

In [99]:
cur = conn.cursor()

In [100]:
cur.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cur.fetchall())

[]


In [101]:
# Create table
cur.execute('''CREATE TABLE IF NOT EXISTS stocks
             (date text, trans text, symbol text, qty real, price real)''')

# Insert a row of data
cur.execute("INSERT INTO stocks VALUES ('2006-01-05','BUY','RHAT',100,35.14)")

# Save (commit) the changes
conn.commit()

# We can also close the connection if we are done with it.
# Just be sure any changes have been committed or they will be lost.
conn.close()

In [102]:
conn = sqlite3.connect(os.path.join(outputs,'example.db'))
cur = conn.cursor()

In [103]:
cur.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cur.fetchall())

[('stocks',)]


In [104]:
t = ('RHAT',) #tuple with just one element
cur.execute('SELECT * FROM stocks WHERE symbol=?', t)
print(cur.fetchone())

('2006-01-05', 'BUY', 'RHAT', 100.0, 35.14)


In [105]:
# Larger example that inserts many records at a time
purchases = [('2006-03-28', 'BUY', 'IBM', 1000, 45.00),
             ('2006-04-05', 'BUY', 'MSFT', 1000, 72.00),
             ('2006-04-06', 'SELL', 'IBM', 500, 53.00),
            ]
cur.executemany('INSERT INTO stocks VALUES (?,?,?,?,?)', purchases)

In [106]:
for row in cur.execute('SELECT * FROM stocks ORDER BY price'):
        print(row)

('2006-01-05', 'BUY', 'RHAT', 100.0, 35.14)
('2006-03-28', 'BUY', 'IBM', 1000.0, 45.0)
('2006-04-06', 'SELL', 'IBM', 500.0, 53.0)
('2006-04-05', 'BUY', 'MSFT', 1000.0, 72.0)


#### Using Pandas

In [107]:
conn = sqlite3.connect(os.path.join(outputs,'example.db'))
df = pd.read_sql_query("SELECT * from stocks ORDER BY price", conn)

# verify that result of SQL query is stored in the dataframe
print(df.head())

conn.close()

         date trans symbol    qty  price
0  2006-01-05   BUY   RHAT  100.0  35.14


Deleting the database file:  

In [108]:
os.remove(os.path.join(outputs,'example.db'))

### Acessing [MySQL](https://pypi.python.org/pypi/PyMySQL)    

In [ ]:
import pymysql

In [ ]:
p = getpass.getpass()
conn = pymysql.connect(host='localhost', port=3306, user='root', passwd=p,)# db='example')
cur = conn.cursor()

In [ ]:
cur.execute("show databases;")
for r in cur.fetchall():
   print(r)

In [ ]:
cur.execute("use mysql;")
cur.execute("show tables;")
for r in cur.fetchall():
   print(r)

In [ ]:
cur.execute("CREATE DATABASE IF NOT EXISTS test;")
cur.execute("USE test;")
cur.execute('''CREATE TABLE IF NOT EXISTS test_table 
               (text VARCHAR(200)
               DEFAULT NULL)
               ENGINE=MyISAM DEFAULT CHARSET='utf8';''')

cur.execute("show tables;")
for r in cur.fetchall():
   print(r)

In [ ]:
texts = ['It always seems impossible until its done.',
         'In order to succeed, we must first believe that we can.',
         'Life is 10% what happens to you and 90% how you react to it.',
         'Start where you are. Use what you have. Do what you can.',]
cur.executemany('INSERT INTO test.test_table (text) VALUES (%s)', texts)



In [ ]:
cur.execute("SELECT * FROM test.test_table;")# LIMIT 10;")
for r in cur.fetchall():
   print(r)

#### Using Pandas

In [ ]:
import pandas.io.sql as psql

In [ ]:
df_mysql = psql.read_sql('select * from test.test_table;', con=conn)

In [ ]:
df_mysql.head()

In [ ]:
cur.close()
conn.close()

### Acessing [PostgreSQL](https://www.psycopg.org/docs/)   

In [ ]:
import psycopg2

In [ ]:
p = getpass.getpass()
try:
    conn = psycopg2.connect("dbname='testdb' user='rsouza' host='localhost' password='{}'".format(p))
except:
    print("I am unable to connect to the database")
cur = conn.cursor()

In [ ]:
cur.execute('SELECT * FROM postgres LIMIT 2;')
for r in cur.fetchall():
   print(r)

#### Using Pandas

In [ ]:
p = getpass.getpass()
try:
    conn = psycopg2.connect("dbname='postgres' user='rsouza' host='localhost' password='{}'".format(p))
except:
    print("I am unable to connect to the database")

In [ ]:
df_postgres = psql.read_sql('SELECT * FROM postgres LIMIT 5;', con=conn)
df_postgres.head()

### Acessing Mongo DB

http://api.mongodb.org/python/current/tutorial.html

In [ ]:
from pymongo import MongoClient

In [ ]:
client = MongoClient()
#client = MongoClient('localhost', 27017)
db = client.test_database #acessa ou cria o banco

## dropping a database via pymongo
#client.drop_database('test_database')

In [ ]:
post = {"author": "Renato",
        "text": "My first blog post!",
        "tags": ["mongodb", "python", "pymongo"],
        "date": datetime.datetime.utcnow()}

In [ ]:
posts = db.posts # cria a coleção
post_id = posts.insert_one(post) #insere dados
post_id

## drop a collection via pymongo
#client['test_database'].drop_collection('posts')

In [ ]:
db.collection_names()

In [ ]:
posts.find_one()

In [ ]:
new_posts = [{"author": "Mike",
              "text": "Another post!",
              "tags": ["bulk", "insert"],
              "date": datetime.datetime(2009, 11, 12, 11, 14)},
             {"author": "Eliot",
              "title": "MongoDB is fun",
              "text": "and pretty easy too!",
              "date": datetime.datetime(2009, 11, 10, 10, 45)}]

In [ ]:
posts.insert_many(new_posts)

In [ ]:
posts.find_one({"author": "Mike"})

In [ ]:
#for post in posts.find({"author": "Mike"}):
for post in posts.find():
    print(post)

In [ ]:
posts.count()

#### Using Pandas

In [ ]:
example_pd = posts.find()
df_pandas =  pd.DataFrame(list(example_pd))
df_pandas

## Accessing Feeds RSS

http://www.feedparser.org/  
http://docs.python.org/library/re.html  
http://www.pythonware.com/library/pil/handbook/index.htm  

In [ ]:
import feedparser

In [ ]:
d = feedparser.parse('https://oglobo.globo.com/rss.xml')

In [ ]:
print(d['feed']['title'])
print(d['feed']['link'])
#print(d.feed.subtitle)
print(len(d['entries']))

In [ ]:
print(d['entries'][0]['title']) 
print(d.entries[0]['link'])

In [ ]:
print(d.headers)

In [ ]:
for post in d.entries:
    print(post.title + ": " + post.link + "\n")

## Accessing Twitter

https://github.com/bear/python-twitter  
Go to http://twitter.com/apps/new to create an app and get these items  
See https://dev.twitter.com/docs/auth/oauth for more information on Twitter's OAuth implementation  
https://dev.twitter.com/rest/reference/get/account/verify_credentials  
https://dev.twitter.com/oauth/overview/application-owner-access-tokens  

In [ ]:
import twitter

In [ ]:
with open('/Documents/MMD/notebooks/twitter_tokens.txt', 'r') as twitter_tokens:
    tokens = twitter_tokens.read().split(',')
consumer_key = tokens[0].strip()
consumer_secret = tokens[1].strip()
access_token = tokens[2].strip()
access_token_secret = tokens[3].strip()

Construct, sign, and open a twitter request using the hard-coded credentials above.

In [ ]:
api = twitter.Api(consumer_key=consumer_key, consumer_secret=consumer_secret, 
                  access_token_key=access_token, access_token_secret=access_token_secret)

In [ ]:
print(api.VerifyCredentials())

In [ ]:
users = api.GetFriends()
print([u.name for u in users])

In [ ]:
followers = api.GetFollowers()
print([u.screen_name for u in followers])

In [ ]:
mentions = api.GetMentions()
#mentions[0].text
print([m.text for m in mentions])

In [ ]:
statuses = api.GetUserTimeline(screen_name='TIME')
print([s.text for s in statuses])

## Dealing with Big Files

Retrieving the file:

In [85]:
link = 'http://eforexcel.com/wp/wp-content/uploads/2017/07/1500000%20Sales%20Records.zip'

In [86]:
urllib.request.urlretrieve(link, "../datasets/CSVs/bigcsv.zip")

('../datasets/CSVs/bigcsv.zip', <http.client.HTTPMessage at 0x7fbc4ebe47f0>)

Using Pandas with chunks:

In [90]:
chunksize = 10 ** 5
num_chunks_to_read = 3

with ZipFile("../datasets/CSVs/bigcsv.zip", 'r') as myzip:
    with myzip.open('1500000 Sales Records.csv') as myfile:
        chunks = pd.read_csv((myfile), chunksize=chunksize) #, iterator=True)
        for i in range(num_chunks_to_read):
            print('Retrieving a new chunk')
            df = chunks.get_chunk()
            print(df.head(3))
            print()

Retrieving a new chunk
                         Region           Country Item Type Sales Channel  \
0            Sub-Saharan Africa      South Africa    Fruits       Offline   
1  Middle East and North Africa           Morocco   Clothes        Online   
2         Australia and Oceania  Papua New Guinea      Meat       Offline   

  Order Priority Order Date   Order ID   Ship Date  Units Sold  Unit Price  \
0              M  7/27/2012  443368995   7/28/2012        1593        9.33   
1              M  9/14/2013  667593514  10/19/2013        4611      109.28   
2              M  5/15/2015  940995585    6/4/2015         360      421.89   

   Unit Cost  Total Revenue  Total Cost  Total Profit  
0       6.92       14862.69    11023.56       3839.13  
1      35.84      503890.08   165258.24     338631.84  
2     364.69      151880.40   131288.40      20592.00  

Retrieving a new chunk
                       Region      Country      Item Type Sales Channel  \
100000     Sub-Saharan Africa   

Unzipping the file and reading line by line:

In [91]:
with ZipFile("../datasets/CSVs/bigcsv.zip", 'r') as myzip:
    myzip.extractall("../datasets/CSVs/")
    myzip.close()

In [92]:
def getstuff(filename):
    with open(filename, "r") as csvfile:
        datareader = csv.reader(csvfile)
        count = 0
        for row in datareader:
            yield(row)

In [93]:
count = 0
for row in getstuff("../datasets/CSVs/1500000 Sales Records.csv"):
    print(row)
    count +=1
    if count > 30:
        break

['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority', 'Order Date', 'Order ID', 'Ship Date', 'Units Sold', 'Unit Price', 'Unit Cost', 'Total Revenue', 'Total Cost', 'Total Profit']
['Sub-Saharan Africa', 'South Africa', 'Fruits', 'Offline', 'M', '7/27/2012', '443368995', '7/28/2012', '1593', '9.33', '6.92', '14862.69', '11023.56', '3839.13']
['Middle East and North Africa', 'Morocco', 'Clothes', 'Online', 'M', '9/14/2013', '667593514', '10/19/2013', '4611', '109.28', '35.84', '503890.08', '165258.24', '338631.84']
['Australia and Oceania', 'Papua New Guinea', 'Meat', 'Offline', 'M', '5/15/2015', '940995585', '6/4/2015', '360', '421.89', '364.69', '151880.40', '131288.40', '20592.00']
['Sub-Saharan Africa', 'Djibouti', 'Clothes', 'Offline', 'H', '5/17/2017', '880811536', '7/2/2017', '562', '109.28', '35.84', '61415.36', '20142.08', '41273.28']
['Europe', 'Slovakia', 'Beverages', 'Offline', 'L', '10/26/2016', '174590194', '12/4/2016', '3973', '47.45', '31.79', '188518.85'

## Using [HDF5](https://portal.hdfgroup.org/display/HDF5/HDF5)  
install: sudo pip3 install h5py  

In [96]:
import h5py

arr = np.random.randn(1000)

#with h5py.File(outputs / 'random.hdf5', 'a') as f:   #if we'd like to append data
with h5py.File(outputs / 'random.hdf5', 'w') as f:
    dset = f.create_dataset("default", data=arr)

In [102]:
with h5py.File(outputs / 'random.hdf5', 'r') as f:
    for key in f.keys():
       print("datasets in ths hdf system:", key)
    
    data = f['default']
    print(type(data))
    print(min(data))
    print(max(data))
    print(data[:15])

datasets in ths hdf system: default
<class 'h5py._hl.dataset.Dataset'>
-3.3765271640356636
2.7813611665017985
[-0.59524694 -1.00467046  1.11106668  0.15856254 -1.18011689  2.11691762
 -1.28100563  1.66229257  1.46906172  1.03215762  0.59811781 -0.92691749
 -0.10675675  0.42983497 -0.87583951]


In [103]:
arr1 = np.random.randn(10000)
arr2 = np.random.randn(10000)

with h5py.File(outputs / 'complex_read.hdf5', 'w') as f:
    f.create_dataset('array_1', data=arr1)
    f.create_dataset('array_2', data=arr2)

In [106]:
with h5py.File(outputs / 'complex_read.hdf5', 'r') as f:
    d1 = f['array_1']
    d2 = f['array_2']
    print(type(d1))
    print(type(d2))
    #data = d2[d1>0]  #error
    data = d2[d1[:]>0]
    print(data)

<class 'h5py._hl.dataset.Dataset'>
<class 'h5py._hl.dataset.Dataset'>
[-0.06510376  0.00332522  0.95322672 ...  0.35694943 -1.1481764
  0.64560298]


## Using Dask:

Read CSV¶

First we read our csv data.

CSV and other text-based file formats are the most common storage for data from many sources, because they require minimal pre-processing, can be written line-by-line and are human-readable. Since Pandas' read_csv is well-optimized, CSVs are a reasonable input, but far from optimized, since reading required extensive text parsing.

In [ ]:
import dask
import dask.dataframe as dd
from dask import delayed, compute

df_csv = dd.read_csv('../datasets/CSVs/1500000 Sales Records.csv')
df_csv.head()

In [ ]:
df_csv.visualize()

In [ ]:
target = ('../datasets/CSVs/1500000 Sales Records.hdf')
target

In [ ]:
%time df.to_hdf(target, '/data')

In [ ]:
# same data as before
df_hdf = dd.read_hdf(target, '/data')
df_hdf.head()

Compare CSV to HDF5 speeds

We do a simple computation that requires reading a column of our dataset and compare performance between CSV files and our newly created HDF5 file. Which do you expect to be faster?

In [ ]:
%time df_csv['Total Profit'].sum().compute()

In [ ]:
%time df_hdf['Total Profit'].sum().compute()

Sadly they are about the same, or perhaps even slower.

The culprit here are the columns which is of object dtype and thus hard to store efficiently. There are two problems here:
 - How do we store text data like names efficiently on disk?
 - Why did we have to read the names column when all we wanted was amount?  